config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'decks#index'

  resources :decks, only: [:show, :index] do
    resources :rounds, only: [:create, :destroy, :show] do
      resources :cards, only: [:show] do
        resources :guesses, only: [:create]
      end
    end
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # get '/signup', to: 'users#new'
  # post '/users', to: 'users#create'

  resources :users, only: [:new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :deck
  has_many :guesses
  has_many :rounds, through: :guesses

end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :cards
  has_many :rounds
  has_many :guesses, through: :rounds, source: :user

  # def shuffle_cards
  #   self.cards.shuffle
  # end

  def get_next_card

  end

  def rotate
    randomized_ids = self.cards.pluck(:id).rotate
    rotated_cards = []

    randomized_ids.each do |id|
      rotated_cards << Card.find(id)
    end

    rotated_cards
  end

end

# get_next_card method
# if correct guess, can't get that card anymore
# If all cards answered correctly, go to success page of some sort
  # later, refactor to rounds and stats.

app/models/guess.rb
class Guess < ApplicationRecord
  belongs_to :round
  belongs_to :card
  has_one :user, through: :round

  def self.create_and_check_guess(card, answer, round)
    Guess.create(correct?: (answer.downcase.chomp == card.answer.downcase), round_id: round.id, card_id: card.id)
  end

  def self.get_correct_cards(guesses)
    correct_cards = []

    guesses.each do |guess|
      correct_cards << guess.card
    end

    correct_cards
  end
end

app/models/round.rb
class Round < ApplicationRecord
  has_many :guesses
  belongs_to :user
  belongs_to :deck
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :rounds
  has_many :guesses, through: :rounds

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

private
  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_round
    @current_round ||= Round.find(session[:round_id]) if session[:round_id]
  end

  helper_method :current_user
  helper_method :logged_in?
  helper_method :current_round
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def show
    @card = Card.find(params[:id])
    @deck = @card.deck
    @round = current_round
    @guess =
  end

end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  def index
    @decks = Deck.all
  end

  def show
    @deck = Deck.find(params[:id])
    @cards = @deck.cards.shuffle
    @card = @cards.first
    render '/cards/show'
  end

end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  def create
    @card = Card.find(params[:card])
    @deck = Deck.find(params[:deck_id]) # make sure to include in form
    @answer = params[:answer]
    @guess = Guess.create_and_check_guess(@card, @answer)

    correct_guesses = @deck.round.guesses.where(correct?: true)
    rotated_cards = @deck.rotate
    @current_cards = rotated_cards - get_correct_cards(correct_guesses)
  end

  private
    def guess_params
      params.require(:guess).permit(:correct?, :round_id, :card_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to decks_path
    else
      redirect_to '/login'
    end
  end

   def destroy
      session[:user_id] = nil
      redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      @errors = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/show.html.erb
<h2><%= @deck.category%></h2>

<%= @card.question %>

<h3>Submit an Answer<h3>
<%= form_for [@deck, @round, @card, @guess] do |f| %>
  <%= f.label :answer %>
  <%= f.text_field :answer %>
  <%= f.submit %>
<% end %>

app/views/decks/index.html.erb
<h2>Decks</h2>
<ul>
<% @decks.each do |deck|%>
  <li><%= link_to(deck.category, deck_path(deck)) %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flashcards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

      <%= link_to "Home", root_path %>
      <% if logged_in? %>
        <p>Hi, <%= current_user.email %>! </p>
        <%= link_to "Logout", logout_path %>
      <% else %>
       <li class=“active”>
         <%= link_to "Sign Up", '/users/new' %>
       </li>
       <li class=“active”>
         <%= link_to "Login", '/login' %>
       </li>
       <% end %>

     </ul>
   </div><!-- /.navbar-collapse -->
 </div><!-- /.container-fluid -->
</nav>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<div class=“container”>
 <h1>Sign Up!</h1>
 <%= form_with model: @user, local: true do |f| %>
   <div class=“form-group”>
     <%= f.label :email %>
     <%= f.text_field :email %>
   </div>
   <div class=“form-group”>
     <%= f.label :password %>
     <%= f.password_field :password %>
   </div>
   <%= f.submit %>
 <% end %>
</div>